travis:
  secure:
    BINSTAR_TOKEN: mijnIYP5mdZ2Cpk3Y+b7307PoEX6Y40F5GYUkTwEfMuYSAC4/C5JOoGbkPHWNe4kwA2FVBQ7RCReTZFNQObOYjkFJif53KH7ZMTmJzBXpfrz9mbOHoBY6VBYRWLRLi9ru1Jjmk2UEJHZ5700jqSX5Rgu6rf46kPGPMBCCOIc5Ujpj1vE1VLt+tQT3lm9OtaOHhUIMIJJMeEo0CMgu9xzGuQrWdADjl6yBoH1c6m/gmyb3yj9UagPGAJhkBCNp87bn7EV6SD1asGTPJ7zFAlEtvicwz9hrXE9nKrIDJ0G1LjaOG3MNTrRFnQwxLK5WNAP4WGdPTQTALwnKVrmQNelBmeVhpBvOBoBDWhAbk3TYW/Vshc2XRQ7f11/Gl3LGBLFtcBv5cB6LUq5A5VWz4I0TmHMtYUsRDIx+dOiVnxlQDPoTdLEYgIGy7b0SeLA9fcKEw/vy6CZRDdy878MJo7lCnCoc86IFEFvSgGF3VkiIZ4ucwXbhJB4ZFHRYHrlkx/GePg4OONhTfwphszfn6cT+0sqEv03T/UN+zkF/V/rj6q7O6TTWy4kk9mLtVmoWiGJHIx7WHANGHiuf3iX03ExZCAbusZ15rwouGepU+aqXelAOM9NyL4u1aLk4Y3ReTmE6VmFvj1WaCJO+i2dWkLnVCAEz/OWdUepLcLDysDHssc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
